### ISSUE TITLE
check mujoco dependency only when enable_continuous=True

### ISSUE THREAD

**Issue by jingweiz** [jingweiz/pytorch-rl#4]
@onlytailei 
We should only require this dependency when enable_continuous=True. Can you check it first?

**Comment by onlytailei** [comment]
@jingweiz 
Yes. Will revise it soon.

**Comment by jingweiz** [comment]
@onlytailei 
Just change the default config to 5 and change a bit in README, should be fine now, can you pull the latest version and check it?

**Comment by onlytailei** [comment]
@jingweiz 
I find that this is no explicit dependency with mujoco (like import mujoco) in pytorch-rl.
It is a implicit dependency in gym only if you try to start the related environments like "InvertedPendulum-v1"  (https://gym.openai.com/envs#mujoco)

**Comment by onlytailei** [comment]
It is better that enable_continuous=True can be connected with the environment and set automatically.
