### ISSUE TITLE
Recurrent DQN

### ISSUE THREAD

**Issue by ghost** [jingweiz/pytorch-rl#9]
Hi,
Would it be possible to implement a Recurrent DQN for partially observable tasks as in [https://arxiv.org/abs/1507.06527] ?

**Comment by jingweiz** [comment]
Hey,
Thanks for the suggestion, I think it would be pretty straight forward to add that in this repo, just need to add an LSTM layer after the last convolution layer in the corresponding dqn model then that's it. I don't think I would have time for that, but it would at most take 3 lines code :)
Cheers
